/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coba;

/**
 *
 * @author glady
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.Color;




public class Driver extends javax.swing.JFrame {

    /**
     * Creates new form Driver
     */
    public Driver() {
        initComponents();
        updData();
        btnSave.setEnabled(false); // Aktifkan tombol Save        
        btnCancel.setEnabled(false);
        setTextFieldsEditable(false);
        jTable1.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
            loadSelectedRowDataToFields(); // Memuat data baris terpilih ke JTextField
        }
        ButSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ButSearchActionPerformed(evt);
        }
    });
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButSearch = new javax.swing.JButton();
        jTextField_Search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButFirst = new javax.swing.JButton();
        ButPrev = new javax.swing.JButton();
        ButNext = new javax.swing.JButton();
        ButLast = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_driverid = new javax.swing.JTextField();
        jTextField_drivername = new javax.swing.JTextField();
        jTextField_phonedriver = new javax.swing.JTextField();
        jTextField_licenseplate = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 194, 194));

        ButSearch.setText("Search");
        ButSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSearchActionPerformed(evt);
            }
        });

        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Driver ID", "Driver Name", "Phone Driver", "License Plate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ButFirst.setText("<<");
        ButFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButFirstActionPerformed(evt);
            }
        });

        ButPrev.setText("<");
        ButPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButPrevActionPerformed(evt);
            }
        });

        ButNext.setText(">");
        ButNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButNextActionPerformed(evt);
            }
        });

        ButLast.setText(">>");
        ButLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButLastActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Driver");

        jLabel2.setText("Driver Name");

        jLabel3.setText("Phone Driver");

        jLabel4.setText("License plate");

        jTextField_driverid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_driveridActionPerformed(evt);
            }
        });

        jTextField_drivername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_drivernameActionPerformed(evt);
            }
        });

        jTextField_phonedriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phonedriverActionPerformed(evt);
            }
        });

        jTextField_licenseplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_licenseplateActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jButton1.setText("<< back");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNew)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDel)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ButFirst)
                                        .addGap(38, 38, 38)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_licenseplate, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(jTextField_drivername)
                                    .addComponent(jTextField_driverid)
                                    .addComponent(jTextField_phonedriver, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ButPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(ButNext, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButLast))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButSearch)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSearch)
                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButFirst)
                    .addComponent(ButPrev)
                    .addComponent(ButNext)
                    .addComponent(ButLast))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_driverid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_drivername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_phonedriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_licenseplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnEdit)
                    .addComponent(btnDel)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void ButFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButFirstActionPerformed
    currentRow = 0; 
    jTable1.setRowSelectionInterval(currentRow, currentRow); 
    updFields(); 
    updTombolNav();
    }//GEN-LAST:event_ButFirstActionPerformed

    private void ButLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButLastActionPerformed
    currentRow = jTable1.getRowCount() - 1; // Baris terakhir
    jTable1.setRowSelectionInterval(currentRow, currentRow); 
    updFields(); 
    updTombolNav(); 
    }//GEN-LAST:event_ButLastActionPerformed

    private void jTextField_driveridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_driveridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_driveridActionPerformed

    private void jTextField_drivernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_drivernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_drivernameActionPerformed

    private void jTextField_phonedriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phonedriverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phonedriverActionPerformed

    private void jTextField_licenseplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_licenseplateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_licenseplateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        toggleAdd = true; // Aktifkan mode penambahan data baru
        setTextFieldsEditable(true);
        ClearText(); // Kosongkan semua JTextField
        btnSave.setEnabled(true); // Aktifkan tombol Save        
        btnCancel.setEnabled(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (toggleAdd) { // Jika dalam mode penambahan data baru
        String idDriver = jTextField_driverid.getText().trim();
        String drivername = jTextField_drivername.getText().trim();
        String phonedriver = jTextField_phonedriver.getText().trim();
        String licenseplate = jTextField_licenseplate.getText().trim();

        // Validasi input
        if (idDriver.isEmpty() || drivername.isEmpty() || phonedriver.isEmpty() || licenseplate.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String connectionUrl =
                "jdbc:sqlserver://GLADYSABELVG:1433;" +
                "database=SAMFOOD;" +
                "user=Gladys Abel;" +
                "password=231525;" +
                "encrypt=true;" +
                "trustServerCertificate=true;" +
                "loginTimeout=30;";
        String insertQuery = "INSERT INTO Driver (driver_id, driver_name, phone_driver, license_plate) VALUES (?, ?, ?, ?, ?)";

        try (Connection connection = DriverManager.getConnection(connectionUrl);
             PreparedStatement statemnt = connection.prepareStatement(insertQuery)) {

            // Set parameter SQL
            statemnt.setInt(1, Integer.parseInt(idDriver));
            statemnt.setString(2, drivername);
            statemnt.setString(3, phonedriver);
            statemnt.setString(4, licenseplate);

            // Eksekusi query
            statemnt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Reset status dan perbarui tabel
            toggleAdd = false;
            btnSave.setEnabled(false);
            btnCancel.setEnabled(false);
            jTextField_driverid.setEditable(false);
            updData(); // Memuat ulang data di tabel
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menambahkan data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }else if (isEditing) {
        // Logika untuk mengupdate data
        updateData();
        
        }else if (toggleDel) { // Jika dalam mode delete
            String driver_id = jTextField_driverid.getText().trim();

            if (driver_id.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih untuk dihapus.", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
        }

        String queryHapus = "DELETE FROM Driver WHERE driver_id = ?";
        String connectionUrl =
               "jdbc:sqlserver://GLADYSABELVG:1433;" +
                "database=SAMFOOD;" +
                "user=Gladys Abel;" +
                "password=231525;" +
                "encrypt=true;" +
                "trustServerCertificate=true;" +
                "loginTimeout=30;";
        try (Connection connection = DriverManager.getConnection(connectionUrl);
             PreparedStatement statemnt = connection.prepareStatement(queryHapus)) {

            // Set parameter SQL
            statemnt.setInt(1, Integer.parseInt(driver_id));

            // Eksekusi query
            statemnt.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Reset status dan perbarui tabel
            toggleDel = false;
            btnSave.setEnabled(false);
            btnCancel.setEnabled(false);
            resetWarnaText();
             btnNew.setEnabled(true);
            btnEdit.setEnabled(true);
            btnDel.setEnabled(true);
            updData(); // Memuat ulang data di tabel
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
        resetWarnaText();
        setTextFieldsEditable(false); 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void ButNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButNextActionPerformed
        if (currentRow < jTable1.getRowCount() - 1) { // Pastikan tidak melewati baris terakhir
        currentRow++;
        jTable1.setRowSelectionInterval(currentRow, currentRow); // Pilih baris berikutnya
        updFields(); // Perbarui JTextField berdasarkan baris
    }
    updTombolNav(); 
    }//GEN-LAST:event_ButNextActionPerformed

    private void ButPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButPrevActionPerformed
        if (currentRow > 0) { // Pastikan tidak melewati baris pertama
        currentRow--;
        jTable1.setRowSelectionInterval(currentRow, currentRow); // Pilih baris sebelumnya
        updFields(); // Perbarui JTextField berdasarkan baris
    }
    updTombolNav(); // Perbarui status tombol navigasi
    }//GEN-LAST:event_ButPrevActionPerformed

    private void ButSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSearchActionPerformed
        String queryCari = jTextField_Search.getText().trim(); // Ambil teks pencarian
        String connectionUrl =
           "jdbc:sqlserver://GLADYSABELVG:1433;" +
            "database=SAMFOOD;" +
            "user=Gladys Abel;" +
            "password=231525;" +
            "encrypt=true;" +
            "trustServerCertificate=true;" +
            "loginTimeout=30;";
    try (Connection connection = DriverManager.getConnection(connectionUrl);
         PreparedStatement statement = connection.prepareStatement(queryCari.isEmpty() ? "SELECT * FROM Driver" : "SELECT * FROM Driver WHERE driver_name LIKE ?"
         )) {

        if (!queryCari.isEmpty()) {
            statement.setString(1, "%" + queryCari + "%"); // Menggunakan wildcard untuk pencarian
        }

        try (ResultSet resultSet = statement.executeQuery()) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Kosongkan tabel sebelum menampilkan hasil baru

            while (resultSet.next()) {
                // Tambahkan hasil ke JTable
                Object[] row = {
                    resultSet.getInt("driver_id"),
                    resultSet.getString("driver_name"),
                    resultSet.getString("phone_driver"),
                    resultSet.getString("license_plate"),
        
                };
                model.addRow(row);
            }

            if (model.getRowCount() > 0) {
                currentRow = 0; // Reset ke baris pertama
                jTable1.setRowSelectionInterval(currentRow, currentRow);
                updFields(); // Perbarui JTextField berdasarkan hasil pertama
            } else {
                ClearText(); // Kosongkan JTextField jika tidak ada data
            }

            updTombolNav(); // Perbarui tombol navigasi
        }
    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencari data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_ButSearchActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
       btnSave.setEnabled(true);
    btnCancel.setEnabled(true);

    // Nonaktifkan tombol lain
    btnNew.setEnabled(false);
    btnEdit.setEnabled(false);
    btnDel.setEnabled(false);

    // Ubah warna teks pada JTextField menjadi merah
      jTextField_driverid.setForeground(Color.RED);
     jTextField_drivername.setForeground(Color.RED);
     jTextField_phonedriver.setForeground(Color.RED);
    jTextField_licenseplate.setForeground(Color.RED);

    toggleDel = true; // Tandai bahwa mode delete sedang aktif
    }//GEN-LAST:event_btnDelActionPerformed
private boolean toggleDel = false;
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       if (toggleAdd) { // Hanya berlaku jika sedang dalam mode penambahan data
        toggleAdd = false; // Batalkan mode penambahan data
        btnSave.setEnabled(false); // Nonaktifkan tombol Save
        btnCancel.setEnabled(false); // Nonaktifkan tombol Cancel
       jTextField_driverid.setEditable(false); // Kunci kembali kolom ID User

        // Kembalikan data JTextField sesuai baris yang saat ini dipilih di tabel
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            jTextField_driverid.setText(jTable1.getValueAt(selectedRow, 0).toString());
            jTextField_drivername.setText(jTable1.getValueAt(selectedRow, 1).toString());
            jTextField_phonedriver.setText(jTable1.getValueAt(selectedRow, 2).toString());
            jTextField_licenseplate.setText(jTable1.getValueAt(selectedRow, 3).toString());
        } else {
            ClearText(); // Jika tidak ada baris yang dipilih, kosongkan JTextField
            }
        }else if (isEditing) {
        // Logika untuk membatalkan pengeditan data
        isEditing = false;
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);

        // Kembalikan data JTextField sesuai baris yang saat ini dipilih di tabel
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            jTextField_driverid.setText(jTable1.getValueAt(selectedRow, 0).toString());
            jTextField_drivername.setText(jTable1.getValueAt(selectedRow, 1).toString());
            jTextField_phonedriver.setText(jTable1.getValueAt(selectedRow, 2).toString());
            jTextField_licenseplate.setText(jTable1.getValueAt(selectedRow, 3).toString());
  
        }
    }else if ((toggleDel)) {
        jTextField_driverid.setForeground(Color.BLACK);
        jTextField_drivername.setForeground(Color.BLACK);
        jTextField_phonedriver.setForeground(Color.BLACK);
        jTextField_licenseplate.setForeground(Color.BLACK);

        // Reset tombol dan kembalikan ke kondisi awal
        btnSave.setEnabled(false);
        btnCancel.setEnabled(false);
        btnNew.setEnabled(true);
        btnEdit.setEnabled(true);
        btnDel.setEnabled(true);

        toggleDel = false;
            
        }
    }                                         
    private boolean isEditing = false;
    private void btnEditActionPerformed() {                                        
        if (jTable1.getSelectedRow() != -1) { // Pastikan ada baris yang dipilih
        jTextField_driverid.setForeground(Color.RED);
        jTextField_drivername.setForeground(Color.RED);
        jTextField_phonedriver.setForeground(Color.RED);
        jTextField_licenseplate.setForeground(Color.RED);
        isEditing = true; // Aktifkan mode edit
        btnSave.setEnabled(true); // Aktifkan tombol Save
        btnCancel.setEnabled(true); // Aktifkan tombol Cancel
        setTextFieldsEditable(true);
        jTextField_driverid.setEditable(false); // ID User tidak dapat diubah
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih data yang ingin diedit.", "Edit Data", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuAdmin menuadmin1 = new MenuAdmin();
        menuadmin1.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ClearText() {
       jTextField_driverid.setText("");
        jTextField_drivername.setText("");
        jTextField_phonedriver.setText("");
        jTextField_licenseplate.setText("");
    }
    private void updateData() {
        String driverId = jTextField_driverid.getText().trim();
        String drivername = jTextField_drivername.getText().trim();
        String phonedriver = jTextField_phonedriver.getText().trim();
        String licenseplate = jTextField_licenseplate.getText().trim();

    if (driverId.isEmpty() || drivername.isEmpty() || phonedriver.isEmpty() || licenseplate.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String connectionUrl =
            "jdbc:sqlserver://GLADYSABELVG:1433;" +
            "database=SAMFOOD;" +
            "user=Gladys Abel;" +
            "password=231525;" +
            "encrypt=true;" +
            "trustServerCertificate=true;" +
            "loginTimeout=30;";

    String updateQuery = "UPDATE Driver SET driver_name = ?,  phone_driver = ?, license_plate = ? WHERE driver_id = ?";

    try (Connection connection = DriverManager.getConnection(connectionUrl);
         PreparedStatement statement = connection.prepareStatement(updateQuery)) {

        statement.setString(1, drivername);
        statement.setString(2, phonedriver);
        statement.setString(3, licenseplate);
        statement.setInt(5, Integer.parseInt(driverId));

        int rowsUpdated = statement.executeUpdate();
        if (rowsUpdated > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            updData(); // Refresh data di tabel
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Data gagal diperbarui.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat memperbarui data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    // Kembali ke mode normal
    isEditing = false;
    btnSave.setEnabled(false);
    btnCancel.setEnabled(false);
}
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver().setVisible(true);
               String connectionUrl =
            "jdbc:sqlserver://GLADYSABELVG:1433;" +
            "database=SAMFOOD;" +
            "user=Gladys Abel;" +
            "password=231525;" +
            "encrypt=true;" +
            "trustServerCertificate=true;" +
            "loginTimeout=30;";
try {
            // Load the JDBC driver (optional for newer Java versions)
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

            // Create the connection
            Connection connection = DriverManager.getConnection(connectionUrl);

            System.out.println("Koneksi berhasil!");

            // Close the connection (optional)
            connection.close();

        } catch (ClassNotFoundException e) {
            System.err.println("Driver tidak ditemukan: " + e.getMessage());
        } catch (SQLException e) {
            System.err.println("Koneksi gagal: " + e.getMessage());
        }
            }
        });
    }
    private boolean isNavigating = false; // Untuk melacak navigasi
    ResultSet allRS;
    boolean isInserted;
    private int currentRow = 0; // Untuk melacak baris saat ini
    private DefaultTableModel searchModel; // Model untuk hasil pencarian
    private boolean toggleAdd = false;
    
 private void updData() {
    String query = "SELECT * FROM Driver"; // Ganti sesuai nama tabel Anda
    String connectionUrl =
            "jdbc:sqlserver://GLADYSABELVG:1433;" +
            "database=SAMFOOD;" +
            "user=Gladys Abel;" +
            "password=231525;" +
            "encrypt=true;" +
            "trustServerCertificate=true;" +
            "loginTimeout=30;";
    try {
        Connection connection = DriverManager.getConnection(connectionUrl);
        PreparedStatement statement = connection.prepareStatement(query, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        allRS = statement.executeQuery(); // Inisialisasi allRS

        // Model untuk JTable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Membersihkan tabel sebelum diisi

        while (allRS.next()) {
            Object[] row = {
                allRS.getInt("driver_id"), // Ganti dengan nama kolom di tabel Anda
                allRS.getString("driver_name"),
                allRS.getString("phone_driver"),
                allRS.getString("license_plate"),
            };
            model.addRow(row);
        }

        // Pilih baris pertama secara otomatis jika data ada
        if (model.getRowCount() > 0) {
            allRS.first(); // Pindahkan ResultSet ke baris pertama
            loadSelectedRowDataToFields(); // Tampilkan data baris pertama ke JTextField
            
            ButPrev.setEnabled(false);
            ButFirst.setEnabled(false);
            ButNext.setEnabled(true);
            ButLast.setEnabled(true);
        }

    } catch (SQLException e) {
        System.err.println("Error saat mengisi tabel: " + e.getMessage());
    }
    
}
    private void loadSelectedRowDataToFields() {
    try {
        // Pastikan ResultSet tidak null dan berada di baris yang valid
        if (allRS != null && !allRS.isAfterLast() && !allRS.isBeforeFirst()) {
             jTextField_driverid.setText(allRS.getString("driver_id")); // ID User
             jTextField_drivername.setText(allRS.getString("driver_name")); // Username
            jTextField_phonedriver.setText(allRS.getString("phone_driver")); // Password
            jTextField_licenseplate.setText(allRS.getString("license_plate")); // Phone Number
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    
}
    private void resetWarnaText() {
     jTextField_driverid.setForeground(Color.BLACK);
     jTextField_drivername.setForeground(Color.BLACK);
    jTextField_phonedriver.setForeground(Color.BLACK);
   jTextField_licenseplate.setForeground(Color.BLACK);
    
}   
    private void updTombolNav() {
    ButNext.setEnabled(currentRow < jTable1.getRowCount() - 1);
    ButPrev.setEnabled(currentRow > 0);
    ButLast.setEnabled(currentRow < jTable1.getRowCount() - 1);
    ButFirst.setEnabled(currentRow > 0);
}
    private void updFields() {
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
         jTextField_driverid.setText(jTable1.getValueAt(selectedRow, 0).toString());
         jTextField_drivername.setText(jTable1.getValueAt(selectedRow, 1).toString());
        jTextField_phonedriver.setText(jTable1.getValueAt(selectedRow, 2).toString());
        jTextField_licenseplate.setText(jTable1.getValueAt(selectedRow, 3).toString());
       
    }
}
    private void setTextFieldsEditable(boolean editable) {
     jTextField_driverid.setEditable(editable);
     jTextField_drivername.setEditable(editable);
    jTextField_phonedriver.setEditable(editable);
    jTextField_licenseplate.setEditable(editable);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButFirst;
    private javax.swing.JButton ButLast;
    private javax.swing.JButton ButNext;
    private javax.swing.JButton ButPrev;
    private javax.swing.JButton ButSearch;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_driverid;
    private javax.swing.JTextField jTextField_drivername;
    private javax.swing.JTextField jTextField_licenseplate;
    private javax.swing.JTextField jTextField_phonedriver;
    // End of variables declaration//GEN-END:variables
}
